In [15]:
#import necesarry libraries
import pandas as pd

In [11]:
import os
print(os.getcwd())  # shows your current working directory

C:\Users\user\Desktop\Tech-Journey\NLP_SENTIMENT-CLASSIFIER_BEGINNERS

In [17]:
tweets = pd.read_csv("data/tweets.csv")
tweets.describe()

,textID,text,selected_text,sentiment
count,27481,27480,27480,27481
unique,27481,27480,22463,3
top,cb774db0d1,"I`d have responded, if I were going",good,neutral
freq,1,1,199,11118

In [18]:
tweets.head()

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative